CREATE TABLE Students (
  id INT PRIMARY KEY IDENTITY(1,1),
  name NVARCHAR(255) NOT NULL,
  email NVARCHAR(255) NOT NULL,
  regNo NVARCHAR(50) NOT NULL,
  class NVARCHAR(50) NOT NULL,
  fee_balance DECIMAL(10, 2) NOT NULL
);

ALTER TABLE Students
ADD isDeleted BIT NOT NULL DEFAULT 0;
